version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: socmed
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./back-end
    container_name: express-backend
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/socmed
    depends_on:
      - mongodb


  frontend:
    build:
      context: ./front-end
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3001
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
